In [5]:
import pandas as pd

df = pd.read_csv("../data/ventas.csv", sep=",")
df

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.00
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.10
...,...,...,...,...,...,...,...,...
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [6]:
df.shape

(1200, 8)

In [7]:
df.columns.tolist()

['fecha',
 'region',
 'vendedor',
 'producto',
 'categoria',
 'unidades',
 'precio_unitario',
 'descuento']

In [8]:
df.head(5)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1

In [9]:
df.tail()

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
1195,2024-12-30,Este,Luis Gomez,Raton Ergo,Accesorios,4,45,0.00
1196,2024-12-30,Este,Marta Ruiz,Laptop Pro,Tecnologia,13,1200,0.05
1197,2024-12-31,Oeste,Ana Torres,Monitor 27,Tecnologia,2,320,0.05
1198,2024-12-31,Norte,Ana Torres,Monitor 27,Tecnologia,6,320,0.00
1199,2024-12-31,Norte,Marta Ruiz,Raton Ergo,Accesorios,8,45,0.00

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [11]:
df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [12]:
df["precio_unitario"].mean()

np.float64(387.4125)

In [14]:
df["unidades"].std()

np.float64(4.0540241611027135)

In [16]:
df["unidades"].quantile(0.75)

np.float64(11.0)

Leyendo desde una URL

In [20]:
df2 = pd.read_html("https://gist.github.com/netj/8836201")[0]
type(df2)

pandas.DataFrame

In [21]:
df2.head(10)

   Unnamed: 0  sepal.length  sepal.width  petal.length  petal.width variety
0         NaN           5.1          3.5           1.4          0.2  Setosa
1         NaN           4.9          3.0           1.4          0.2  Setosa
2         NaN           4.7          3.2           1.3          0.2  Setosa
3         NaN           4.6          3.1           1.5          0.2  Setosa
4         NaN           5.0          3.6           1.4          0.2  Setosa
5         NaN           5.4          3.9           1.7          0.4  Setosa
6         NaN           4.6          3.4           1.4          0.3  Setosa
7         NaN           5.0          3.4           1.5          0.2  Setosa
8         NaN           4.4          2.9           1.4          0.2  Setosa
9         NaN           4.9          3.1           1.5          0.1  Setosa

Leyendo un JSON

In [22]:
df3 = pd.read_json("../data/Bookings.json")
df3.head(10)

,﻿Date,Time,Booking_ID,Booking_Status,Customer_ID,Vehicle_Type,Pickup_Location,Drop_Location,V_TAT,C_TAT,...,Canceled_Rides_by_Driver,Incomplete_Rides,Incomplete_Rides_Reason,Booking_Value,Payment_Method,Ride_Distance,Driver_Ratings,Customer_Rating,Vehicle Images,
0,2024-07-26 14:00:00,14:00:00,CNR7153255142,Canceled by Driver,CID713523,Prime Sedan,Tumkur Road,RT Nagar,null,null,...,Personal & Car related issue,null,null,444,null,0,null,null,#NAME?,

In [23]:
df3.transpose()

                                                       0
﻿Date                                2024-07-26 14:00:00
Time                                            14:00:00
Booking_ID                                 CNR7153255142
Booking_Status                        Canceled by Driver
Customer_ID                                    CID713523
Vehicle_Type                                 Prime Sedan
Pickup_Location                              Tumkur Road
Drop_Location                                   RT Nagar
V_TAT                                               null
C_TAT                                               null
Canceled_Rides_by_Customer                          null
Canceled_Rides_by_Driver    Personal & Car related issue
Incomplete_Rides                                    null
Incomplete_Rides_Reason                             null
Booking_Value                                        444
Payment_Method                                      null
Ride_Distance                                          0
Driver_Ratings                                      null
Customer_Rating                                     null
Vehicle Images                                    #NAME?

In [24]:
import requests
import pandas as pd

respuesta = requests.get(
    "https://api.open-meteo.com/v1/forecast",
    params={
        "latitude": -16.40,
        "longitude": -71.54,
        "hourly": "temperature_2m,relative_humidity_2m,precipitation",
        "timezone": "America/Lima",
        "forecast_days": 7,
    },
    timeout=30,
)
respuesta.raise_for_status()

In [27]:
respuesta.json()

{'latitude': -16.414762,
 'longitude': -71.58896,
 'generationtime_ms': 0.11599063873291016,
 'utc_offset_seconds': -18000,
 'timezone': 'America/Lima',
 'timezone_abbreviation': 'GMT-5',
 'elevation': 2326.0,
 'hourly_units': {'time': 'iso8601',
  'temperature_2m': '°C',
  'relative_humidity_2m': '%',
  'precipitation': 'mm'},
 'hourly': {'time': ['2026-10-03T00:00',
   '2026-10-03T01:00',
   '2026-10-03T02:00',
   '2026-10-03T03:00',
   '2026-10-03T04:00',
   '2026-10-03T05:00',
   '2026-10-03T06:00',
   '2026-10-03T07:00',
   '2026-10-03T08:00',
   '2026-10-03T09:00',
   '2026-10-03T10:00',
   '2026-10-03T11:00',
   '2026-10-03T12:00',
   '2026-10-03T13:00',
   '2026-10-03T14:00',
   '2026-10-03T15:00',
   '2026-10-03T16:00',
   '2026-10-03T17:00',
   '2026-10-03T18:00',
   '2026-10-03T19:00',
   '2026-10-03T20:00',
   '2026-10-03T21:00',
   '2026-10-03T22:00',
   '2026-10-03T23:00',
   '2026-10-04T00:00',
   '2026-10-04T01:00',
   '2026-10-04T02:00',
   '2026-10-04T03:00',
   '2026-10-04T04:00',
   '2026-10-04T05:00',
   '2026-10-04T06:00',
   '2026-10-04T07:00',
   '2026-10-04T08:00',
   '2026-10-04T09:00',
   '2026-10-04T10:00',
   '2026-10-04T11:00',
   '2026-10-04T12:00',
   '2026-10-04T13:00',
   '2026-10-04T14:00',
   '2026-10-04T15:00',
   '2026-10-04T16:00',
   '2026-10-04T17:00',
   '2026-10-04T18:00',
   '2026-10-04T19:00',
   '2026-10-04T20:00',
   '2026-10-04T21:00',
   '2026-10-04T22:00',
   '2026-10-04T23:00',
   '2026-10-05T00:00',
   '2026-10-05T01:00',
   '2026-10-05T02:00',
   '2026-10-05T03:00',
   '2026-10-05T04:00',
   '2026-10-05T05:00',
   '2026-10-05T06:00',
   '2026-10-05T07:00',
   '2026-10-05T08:00',
   '2026-10-05T09:00',
   '2026-10-05T10:00',
   '2026-10-05T11:00',
   '2026-10-05T12:00',
   '2026-10-05T13:00',
   '2026-10-05T14:00',
   '2026-10-05T15:00',
   '2026-10-05T16:00',
   '2026-10-05T17:00',
   '2026-10-05T18:00',
   '2026-10-05T19:00',
   '2026-10-05T20:00',
   '2026-10-05T21:00',
   '2026-10-05T22:00',
   '2026-10-05T23:00',
   '2026-10-06T00:00',
   '2026-10-06T01:00',
   '2026-10-06T02:00',
   '2026-10-06T03:00',
   '2026-10-06T04:00',
   '2026-10-06T05:00',
   '2026-10-06T06:00',
   '2026-10-06T07:00',
   '2026-10-06T08:00',
   '2026-10-06T09:00',
   '2026-10-06T10:00',
   '2026-10-06T11:00',
   '2026-10-06T12:00',
   '2026-10-06T13:00',
   '2026-10-06T14:00',
   '2026-10-06T15:00',
   '2026-10-06T16:00',
   '2026-10-06T17:00',
   '2026-10-06T18:00',
   '2026-10-06T19:00',
   '2026-10-06T20:00',
   '2026-10-06T21:00',
   '2026-10-06T22:00',
   '2026-10-06T23:00',
   '2026-10-07T00:00',
   '2026-10-07T01:00',
   '2026-10-07T02:00',
   '2026-10-07T03:00',
   '2026-10-07T04:00',
   '2026-10-07T05:00',
   '2026-10-07T06:00',
   '2026-10-07T07:00',
   '2026-10-07T08:00',
   '2026-10-07T09:00',
   '2026-10-07T10:00',
   '2026-10-07T11:00',
   '2026-10-07T12:00',
   '2026-10-07T13:00',
   '2026-10-07T14:00',
   '2026-10-07T15:00',
   '2026-10-07T16:00',
   '2026-10-07T17:00',
   '2026-10-07T18:00',
   '2026-10-07T19:00',
   '2026-10-07T20:00',
   '2026-10-07T21:00',
   '2026-10-07T22:00',
   '2026-10-07T23:00',
   '2026-10-08T00:00',
   '2026-10-08T01:00',
   '2026-10-08T02:00',
   '2026-10-08T03:00',
   '2026-10-08T04:00',
   '2026-10-08T05:00',
   '2026-10-08T06:00',
   '2026-10-08T07:00',
   '2026-10-08T08:00',
   '2026-10-08T09:00',
   '2026-10-08T10:00',
   '2026-10-08T11:00',
   '2026-10-08T12:00',
   '2026-10-08T13:00',
   '2026-10-08T14:00',
   '2026-10-08T15:00',
   '2026-10-08T16:00',
   '2026-10-08T17:00',
   '2026-10-08T18:00',
   '2026-10-08T19:00',
   '2026-10-08T20:00',
   '2026-10-08T21:00',
   '2026-10-08T22:00',
   '2026-10-08T23:00',
   '2026-10-09T00:00',
   '2026-10-09T01:00',
   '2026-10-09T02:00',
   '2026-10-09T03:00',
   '2026-10-09T04:00',
   '2026-10-09T05:00',
   '2026-10-09T06:00',
   '2026-10-09T07:00',
   '2026-10-09T08:00',
   '2026-10-09T09:00',
   '2026-10-09T10:00',
   '2026-10-09T11:00',
   '2026-10-09T12:00',
   '2026-10-09T13:00',
   '2026-10-09T14:00',
   '2026-10-09T15:00',
   '2026-10-09T16:00',
   '2026-10-09T17:00',
   '2026-10-09T18:00',
   '2026-10-09T19:00',
   '2026-10-09T20:00',
   '2026-10-09T21:00',
   '2026-10-09T22:00',
   '2026-10-09T23:00'],
  'temperature_2m': [12.1,
   10.9,
   10.4,
   11.1,
   10.7,
   9.8,
   10.4,
   15.2,
   19.3,
   21.6,
   22.5,
   23.0,
   23.7,
   23.7,
   23.0,
   21.9,
   20.6,
   19.0,
   17.0,
   16.1,
   15.5,
   15.0,
   14.0,
   13.4,
   12.5,
   11.6,
   11.5,
   11.2,
   11.1,
   10.6,
   11.0,
   15.9,
   18.5,
   20.4,
   21.4,
   21.8,
   22.4,
   22.5,
   22.1,
   21.2,
   19.7,
   17.8,
   16.0,
   14.9,
   13.8,
   13.6,
   13.3,
   13.0,
   12.4,
   11.9,
   11.5,
   11.3,
   11.3,
   11.4,
   12.1,
   16.3,
   18.9,
   21.5,
   23.5,
   24.4,
   24.6,
   24.7,
   24.3,
   23.3,
   21.6,
   19.4,
   17.2,
   16.1,
   15.4,
   15.3,
   14.9,
   14.2,
   13.5,
   12.8,
   12.2,
   11.5,
   10.2,
   9.1,
   9.7,
   15.5,
   19.0,
   21.3,
   22.5,
   23.4,
   24.3,
   24.7,
   24.4,
   23.4,
   21.9,
   19.9,
   17.5,
   15.6,
   14.8,
   14.1,
   13.3,
   12.7,
   12.2,
   11.6,
   10.8,
   9.9,
   9.8,
   11.0,
   13.0,
   15.2,
   17.6,
   20.3,
   22.3,
   23.4,
   23.8,
   23.8,
   23.2,
   22.1,
   20.8,
   19.1,
   17.1,
   15.5,
   14.5,
   13.8,
   13.2,
   12.7,
   12.3,
   11.9,
   11.3,
   10.7,
   10.7,
   11.6,
   13.1,
   14.9,
   17.3,
   20.0,
   21.9,
   22.6,
   22.5,
   22.1,
   21.6,
   20.9,
   19.9,
   18.4,
   16.7,
   15.3,
   14.5,
   13.9,
   13.4,
   12.6,
   11.9,
   11.2,
   10.6,
   10.0,
   10.3,
   14.0,
   15.1,
   16.1,
   17.4,
   18.9,
   20.5,
   21.9,
   22.9,
   23.2,
   22.8,
   21.7,
   20.1,
   18.5,
   16.9,
   15.7,
   14.7,
   13.8,
   13.0,
   12.3],
  'relative_humidity_2m': [54,
   57,
   55,
   41,
   29,
   20,
   15,
   13,
   11,
   10,
   12,
   17,
   15,
   14,
   18,
   26,
   29,
   27,
   28,
   32,
   32,
   36,
   43,
   46,
   46,
   38,
   25,
   18,
   17,
   17,
   18,
   16,
   18,
   17,
   20,
   23,
   24,
   23,
   24,
   28,
   33,
   36,
   40,
   43,
   47,
   48,
   50,
   52,
   54,
   56,
   51,
   43,
   35,
   29,
   26,
   20,
   24,
   20,
   18,
   20,
   20,
   17,
   17,
   20,
   23,
   28,
   34,
   38,
   38,
   39,
   39,
   41,
   43,
   43,
   43,
   42,
   37,
   29,
   23,
   17,
   20,
   18,
   17,
   18,
   17,
   17,
   19,
   21,
   22,
   24,
   28,
   33,
   44,
   38,
   42,
   44,
   45,
   47,
   49,
   50,
   48,
   40,
   32,
   25,
   22,
   19,
   18,
   17,
   17,
   19,
   23,
   29,
   35,
   40,
   44,
   47,
   50,
   52,
   53,
   54,
   55,
   52,
   45,
   36,
   31,
   31,
   34,
   34,
   30,
   25,
   22,
   23,
   26,
   29,
   31,
   33,
   36,
   41,
   47,
   53,
   57,
   61,
   63,
   65,
   66,
   65,
   61,
   55,
   48,
   32,
   26,
   23,
   22,
   21,
   22,
   22,
   23,
   24,
   25,
   26,
   28,
   29,
   31,
   34,
   36,
   40,
   44,
   48],
  'precipitation': [0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0,
   0.0]}}

In [28]:
datos = respuesta.json()
df = pd.DataFrame(datos["hourly"])
df["time"] = pd.to_datetime(df["time"])

df.head(10)

                 time  temperature_2m  relative_humidity_2m  precipitation
0 2026-10-03 00:00:00            12.1                    54            0.0
1 2026-10-03 01:00:00            10.9                    57            0.0
2 2026-10-03 02:00:00            10.4                    55            0.0
3 2026-10-03 03:00:00            11.1                    41            0.0
4 2026-10-03 04:00:00            10.7                    29            0.0
5 2026-10-03 05:00:00             9.8                    20            0.0
6 2026-10-03 06:00:00            10.4                    15            0.0
7 2026-10-03 07:00:00            15.2                    13            0.0
8 2026-10-03 08:00:00            19.3                    11            0.0
9 2026-10-03 09:00:00            21.6                    10            0.0

In [33]:
import requests
import pandas as pd

url = "https://pokeapi.co/api/v2/pokemon"

respuesta = requests.get(url, params={"limit": 10}, timeout=30)
respuesta.raise_for_status()

In [34]:
respuesta.json()

{'count': 1351,
 'next': 'https://pokeapi.co/api/v2/pokemon?offset=10&limit=10',
 'previous': None,
 'results': [{'name': 'bulbasaur',
   'url': 'https://pokeapi.co/api/v2/pokemon/1/'},
  {'name': 'ivysaur', 'url': 'https://pokeapi.co/api/v2/pokemon/2/'},
  {'name': 'venusaur', 'url': 'https://pokeapi.co/api/v2/pokemon/3/'},
  {'name': 'charmander', 'url': 'https://pokeapi.co/api/v2/pokemon/4/'},
  {'name': 'charmeleon', 'url': 'https://pokeapi.co/api/v2/pokemon/5/'},
  {'name': 'charizard', 'url': 'https://pokeapi.co/api/v2/pokemon/6/'},
  {'name': 'squirtle', 'url': 'https://pokeapi.co/api/v2/pokemon/7/'},
  {'name': 'wartortle', 'url': 'https://pokeapi.co/api/v2/pokemon/8/'},
  {'name': 'blastoise', 'url': 'https://pokeapi.co/api/v2/pokemon/9/'},
  {'name': 'caterpie', 'url': 'https://pokeapi.co/api/v2/pokemon/10/'}]}

In [35]:
datos = respuesta.json()
df = pd.DataFrame(datos["results"])
df.head()

         name                                   url
0   bulbasaur  https://pokeapi.co/api/v2/pokemon/1/
1     ivysaur  https://pokeapi.co/api/v2/pokemon/2/
2    venusaur  https://pokeapi.co/api/v2/pokemon/3/
3  charmander  https://pokeapi.co/api/v2/pokemon/4/
4  charmeleon  https://pokeapi.co/api/v2/pokemon/5/

In [36]:
respuesta = requests.get("https://pokeapi.co/api/v2/pokemon/1", timeout=30)
respuesta.raise_for_status()
respuesta.json()

{'id': 1,
 'name': 'bulbasaur',
 'base_experience': 64,
 'height': 7,
 'is_default': True,
 'order': 1,
 'weight': 69,
 'abilities': [{'is_hidden': False,
   'slot': 1,
   'ability': {'name': 'overgrow',
    'url': 'https://pokeapi.co/api/v2/ability/65/'}},
  {'is_hidden': True,
   'slot': 3,
   'ability': {'name': 'chlorophyll',
    'url': 'https://pokeapi.co/api/v2/ability/34/'}}],
 'past_abilities': [{'generation': {'name': 'generation-iv',
    'url': 'https://pokeapi.co/api/v2/generation/4/'},
   'abilities': [{'is_hidden': True, 'slot': 3, 'ability': None}]}],
 'forms': [{'name': 'bulbasaur',
   'url': 'https://pokeapi.co/api/v2/pokemon-form/1/'}],
 'game_indices': [{'game_index': 153,
   'version': {'name': 'red', 'url': 'https://pokeapi.co/api/v2/version/1/'}},
  {'game_index': 153,
   'version': {'name': 'blue', 'url': 'https://pokeapi.co/api/v2/version/2/'}},
  {'game_index': 153,
   'version': {'name': 'yellow',
    'url': 'https://pokeapi.co/api/v2/version/3/'}},
  {'game_index': 1,
   'version': {'name': 'gold', 'url': 'https://pokeapi.co/api/v2/version/4/'}},
  {'game_index': 1,
   'version': {'name': 'silver',
    'url': 'https://pokeapi.co/api/v2/version/5/'}},
  {'game_index': 1,
   'version': {'name': 'crystal',
    'url': 'https://pokeapi.co/api/v2/version/6/'}},
  {'game_index': 1,
   'version': {'name': 'ruby', 'url': 'https://pokeapi.co/api/v2/version/7/'}},
  {'game_index': 1,
   'version': {'name': 'sapphire',
    'url': 'https://pokeapi.co/api/v2/version/8/'}},
  {'game_index': 1,
   'version': {'name': 'emerald',
    'url': 'https://pokeapi.co/api/v2/version/9/'}},
  {'game_index': 1,
   'version': {'name': 'firered',
    'url': 'https://pokeapi.co/api/v2/version/10/'}},
  {'game_index': 1,
   'version': {'name': 'leafgreen',
    'url': 'https://pokeapi.co/api/v2/version/11/'}},
  {'game_index': 1,
   'version': {'name': 'diamond',
    'url': 'https://pokeapi.co/api/v2/version/12/'}},
  {'game_index': 1,
   'version': {'name': 'pearl',
    'url': 'https://pokeapi.co/api/v2/version/13/'}},
  {'game_index': 1,
   'version': {'name': 'platinum',
    'url': 'https://pokeapi.co/api/v2/version/14/'}},
  {'game_index': 1,
   'version': {'name': 'heartgold',
    'url': 'https://pokeapi.co/api/v2/version/15/'}},
  {'game_index': 1,
   'version': {'name': 'soulsilver',
    'url': 'https://pokeapi.co/api/v2/version/16/'}},
  {'game_index': 1,
   'version': {'name': 'black',
    'url': 'https://pokeapi.co/api/v2/version/17/'}},
  {'game_index': 1,
   'version': {'name': 'white',
    'url': 'https://pokeapi.co/api/v2/version/18/'}},
  {'game_index': 1,
   'version': {'name': 'black-2',
    'url': 'https://pokeapi.co/api/v2/version/21/'}},
  {'game_index': 1,
   'version': {'name': 'white-2',
    'url': 'https://pokeapi.co/api/v2/version/22/'}},
  {'game_index': 1,
   'version': {'name': 'x', 'url': 'https://pokeapi.co/api/v2/version/23/'}},
  {'game_index': 1,
   'version': {'name': 'y', 'url': 'https://pokeapi.co/api/v2/version/24/'}},
  {'game_index': 1,
   'version': {'name': 'omega-ruby',
    'url': 'https://pokeapi.co/api/v2/version/25/'}},
  {'game_index': 1,
   'version': {'name': 'alpha-sapphire',
    'url': 'https://pokeapi.co/api/v2/version/26/'}},
  {'game_index': 1,
   'version': {'name': 'sun', 'url': 'https://pokeapi.co/api/v2/version/27/'}},
  {'game_index': 1,
   'version': {'name': 'moon',
    'url': 'https://pokeapi.co/api/v2/version/28/'}},
  {'game_index': 1,
   'version': {'name': 'ultra-sun',
    'url': 'https://pokeapi.co/api/v2/version/29/'}},
  {'game_index': 1,
   'version': {'name': 'ultra-moon',
    'url': 'https://pokeapi.co/api/v2/version/30/'}},
  {'game_index': 1,
   'version': {'name': 'lets-go-pikachu',
    'url': 'https://pokeapi.co/api/v2/version/31/'}},
  {'game_index': 1,
   'version': {'name': 'lets-go-eevee',
    'url': 'https://pokeapi.co/api/v2/version/32/'}},
  {'game_index': 1,
   'version': {'name': 'sword',
    'url': 'https://pokeapi.co/api/v2/version/33/'}},
  {'game_index': 1,
   'version': {'name': 'shield',
    'url': 'https://pokeapi.co/api/v2/version/34/'}},
  {'game_index': 1,
   'version': {'name': 'the-isle-of-armor-sword',
    'url': 'https://pokeapi.co/api/v2/version/35/'}},
  {'game_index': 1,
   'version': {'name': 'the-crown-tundra-sword',
    'url': 'https://pokeapi.co/api/v2/version/36/'}},
  {'game_index': 1,
   'version': {'name': 'brilliant-diamond',
    'url': 'https://pokeapi.co/api/v2/version/37/'}},
  {'game_index': 1,
   'version': {'name': 'shining-pearl',
    'url': 'https://pokeapi.co/api/v2/version/38/'}},
  {'game_index': 1,
   'version': {'name': 'legends-arceus',
    'url': 'https://pokeapi.co/api/v2/version/39/'}},
  {'game_index': 1,
   'version': {'name': 'scarlet',
    'url': 'https://pokeapi.co/api/v2/version/40/'}},
  {'game_index': 1,
   'version': {'name': 'violet',
    'url': 'https://pokeapi.co/api/v2/version/41/'}},
  {'game_index': 1,
   'version': {'name': 'the-teal-mask-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/42/'}},
  {'game_index': 1,
   'version': {'name': 'the-indigo-disk-scarlet',
    'url': 'https://pokeapi.co/api/v2/version/43/'}},
  {'game_index': 153,
   'version': {'name': 'red-japan',
    'url': 'https://pokeapi.co/api/v2/version/44/'}},
  {'game_index': 153,
   'version': {'name': 'green-japan',
    'url': 'https://pokeapi.co/api/v2/version/45/'}},
  {'game_index': 153,
   'version': {'name': 'blue-japan',
    'url': 'https://pokeapi.co/api/v2/version/46/'}},
  {'game_index': 1,
   'version': {'name': 'legends-za',
    'url': 'https://pokeapi.co/api/v2/version/47/'}},
  {'game_index': 1,
   'version': {'name': 'mega-dimension',
    'url': 'https://pokeapi.co/api/v2/version/48/'}}],
 'held_items': [],
 'location_area_encounters': 'https://pokeapi.co/api/v2/pokemon/1/encounters',
 'moves': [{'move': {'name': 'razor-wind',
    'url': 'https://pokeapi.co/api/v2/move/13/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'egg',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/2/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'egg',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/2/'},
     'order': None}]},
  {'move': {'name': 'swords-dance',
    'url': 'https://pokeapi.co/api/v2/move/14/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sun-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/17/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'sword-shield',
      'url': 'https://pokeapi.co/api/v2/version-group/20/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'brilliant-diamond-shining-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/23/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'scarlet-violet',
      'url': 'https://pokeapi.co/api/v2/version-group/25/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'cut', 'url': 'https://pokeapi.co/api/v2/move/15/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'heartgold-soulsilver',
      'url': 'https://pokeapi.co/api/v2/version-group/10/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-white',
      'url': 'https://pokeapi.co/api/v2/version-group/11/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'colosseum',
      'url': 'https://pokeapi.co/api/v2/version-group/12/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'xd',
      'url': 'https://pokeapi.co/api/v2/version-group/13/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'x-y',
      'url': 'https://pokeapi.co/api/v2/version-group/15/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'brilliant-diamond-shining-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/23/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'red-green-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/28/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'blue-japan',
      'url': 'https://pokeapi.co/api/v2/version-group/29/'},
     'move_learn_method': {'name': 'machine',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/4/'},
     'order': None}]},
  {'move': {'name': 'bind', 'url': 'https://pokeapi.co/api/v2/move/20/'},
   'version_group_details': [{'level_learned_at': 0,
     'version_group': {'name': 'black-2-white-2',
      'url': 'https://pokeapi.co/api/v2/version-group/14/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'omega-ruby-alpha-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/16/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None},
    {'level_learned_at': 0,
     'version_group': {'name': 'ultra-sun-ultra-moon',
      'url': 'https://pokeapi.co/api/v2/version-group/18/'},
     'move_learn_method': {'name': 'tutor',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/3/'},
     'order': None}]},
  {'move': {'name': 'vine-whip', 'url': 'https://pokeapi.co/api/v2/move/22/'},
   'version_group_details': [{'level_learned_at': 13,
     'version_group': {'name': 'red-blue',
      'url': 'https://pokeapi.co/api/v2/version-group/1/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 13,
     'version_group': {'name': 'yellow',
      'url': 'https://pokeapi.co/api/v2/version-group/2/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'gold-silver',
      'url': 'https://pokeapi.co/api/v2/version-group/3/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'crystal',
      'url': 'https://pokeapi.co/api/v2/version-group/4/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'ruby-sapphire',
      'url': 'https://pokeapi.co/api/v2/version-group/5/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'emerald',
      'url': 'https://pokeapi.co/api/v2/version-group/6/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 10,
     'version_group': {'name': 'firered-leafgreen',
      'url': 'https://pokeapi.co/api/v2/version-group/7/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 9,
     'version_group': {'name': 'diamond-pearl',
      'url': 'https://pokeapi.co/api/v2/version-group/8/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},
    {'level_learned_at': 9,
     'version_group': {'name': 'platinum',
      'url': 'https://pokeapi.co/api/v2/version-group/9/'},
     'move_learn_method': {'name': 'level-up',
      'url': 'https://pokeapi.co/api/v2/move-learn-method/1/'},
     'order': None},

In [37]:
filas = []

for url_pokemon in df["url"]:
    respuesta = requests.get(url_pokemon, timeout=30)
    respuesta.raise_for_status()
    pokemon = respuesta.json()

    filas.append({
        "id": pokemon["id"],
        "nombre": pokemon["name"],
        "altura_m": pokemon["height"] / 10,
        "peso_kg": pokemon["weight"] / 10,
        "tipos": ", ".join(
            elemento["type"]["name"]
            for elemento in pokemon["types"]
        ),
    })

df_pokemon = pd.DataFrame(filas)
df_pokemon.head(50)

   id      nombre  altura_m  peso_kg          tipos
0   1   bulbasaur       0.7      6.9  grass, poison
1   2     ivysaur       1.0     13.0  grass, poison
2   3    venusaur       2.0    100.0  grass, poison
3   4  charmander       0.6      8.5           fire
4   5  charmeleon       1.1     19.0           fire
5   6   charizard       1.7     90.5   fire, flying
6   7    squirtle       0.5      9.0          water
7   8   wartortle       1.0     22.5          water
8   9   blastoise       1.6     85.5          water
9  10    caterpie       0.3      2.9            bug

In [38]:
import requests

url = "https://pokeapi.co/api/v2/berry/2/"

respuesta = requests.get(url, timeout=30)
respuesta.raise_for_status()
respuesta.json()

{'id': 2,
 'name': 'chesto',
 'growth_time': 3,
 'max_harvest': 5,
 'natural_gift_power': 60,
 'size': 80,
 'smoothness': 25,
 'soil_dryness': 15,
 'firmness': {'name': 'super-hard',
  'url': 'https://pokeapi.co/api/v2/berry-firmness/5/'},
 'flavors': [{'potency': 0,
   'flavor': {'name': 'spicy',
    'url': 'https://pokeapi.co/api/v2/berry-flavor/1/'}},
  {'potency': 10,
   'flavor': {'name': 'dry',
    'url': 'https://pokeapi.co/api/v2/berry-flavor/2/'}},
  {'potency': 0,
   'flavor': {'name': 'sweet',
    'url': 'https://pokeapi.co/api/v2/berry-flavor/3/'}},
  {'potency': 0,
   'flavor': {'name': 'bitter',
    'url': 'https://pokeapi.co/api/v2/berry-flavor/4/'}},
  {'potency': 0,
   'flavor': {'name': 'sour',
    'url': 'https://pokeapi.co/api/v2/berry-flavor/5/'}}],
 'item': {'name': 'chesto-berry',
  'url': 'https://pokeapi.co/api/v2/item/127/'},
 'natural_gift_type': {'name': 'water',
  'url': 'https://pokeapi.co/api/v2/type/11/'}}

In [ ]:
#Guardando en fisico este file
df_pokemon.to_csv("../data/pokemons.csv", index=False)

In [40]:
df_pokemon.to_excel("../data/pokemons.xlsx", index=False)