In [1]:
import pandas as pd

ventas_df = pd.read_csv("../data/ventas.csv ")
ventas_df.head(10)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0
4,2024-01-03,Sur,Elena Mora,Auriculares,Accesorios,2,130,0.1
5,2024-01-03,Oeste,Javier Sanz,Escritorio,Mobiliario,2,450,0.0
6,2024-01-03,Norte,Carlos Vega,Silla Ergo,Mobiliario,4,280,0.0
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.0
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.1
9,2024-01-03,Centro,Pedro Diaz,Escritorio,Mobiliario,2,450,0.0

In [2]:
ventas_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   fecha            1200 non-null   str
 1   region           1200 non-null   str
 2   vendedor         1182 non-null   str
 3   producto         1200 non-null   str
 4   categoria        1200 non-null   str
 5   unidades         1200 non-null   int64
 6   precio_unitario  1200 non-null   int64
 7   descuento        1165 non-null   float64
dtypes: float64(1), int64(2), str(5)
memory usage: 75.1 KB

In [3]:
ventas_df.describe()

          unidades  precio_unitario    descuento
count  1200.000000      1200.000000  1165.000000
mean      7.275833       387.412500     0.047639
std       4.054024       346.020316     0.056273
min       1.000000        45.000000     0.000000
25%       4.000000       130.000000     0.000000
50%       7.000000       280.000000     0.000000
75%      11.000000       450.000000     0.100000
max      14.000000      1200.000000     0.150000

In [5]:
#contar valores unicos de una columna
ventas_df["producto"].value_counts()

producto
Silla Ergo     177
Monitor 27     159
Auriculares    158
Tablet Air     149
Raton Ergo     146
Laptop Pro     139
Escritorio     139
Teclado Mec    133
Name: count, dtype: int64

In [8]:
# Analisis de una lista de campos
ventas_df[["vendedor", "producto", "categoria"]]

         vendedor     producto   categoria
0      Pedro Diaz  Auriculares  Accesorios
1      Luis Gomez   Monitor 27  Tecnologia
2     Carlos Vega   Silla Ergo  Mobiliario
3      Pedro Diaz   Laptop Pro  Tecnologia
4      Elena Mora  Auriculares  Accesorios
...           ...          ...         ...
1195   Luis Gomez   Raton Ergo  Accesorios
1196   Marta Ruiz   Laptop Pro  Tecnologia
1197   Ana Torres   Monitor 27  Tecnologia
1198   Ana Torres   Monitor 27  Tecnologia
1199   Marta Ruiz   Raton Ergo  Accesorios

[1200 rows x 3 columns]

LOC

Localiza las filas por indice, dado que las columnas no tienen indice se debe usar su etiqueta, nombre o listarlas si las queremos en conjunto.

In [9]:
# Busqueda de registros indexando con "loc" y de columnas listando con "[]"
ventas_df.loc[0:4,["vendedor", "producto", "categoria"]]

      vendedor     producto   categoria
0   Pedro Diaz  Auriculares  Accesorios
1   Luis Gomez   Monitor 27  Tecnologia
2  Carlos Vega   Silla Ergo  Mobiliario
3   Pedro Diaz   Laptop Pro  Tecnologia
4   Elena Mora  Auriculares  Accesorios

In [12]:
# Del indice 1000 hacia el final, solo se mostrara las columnas "vendedor" y "producto"
ventas_df.loc[1000:,["vendedor", "producto"]]

        vendedor     producto
1000  Luis Gomez  Teclado Mec
1001  Luis Gomez  Teclado Mec
1002  Sofia Leon   Monitor 27
1003  Luis Gomez   Raton Ergo
1004  Luis Gomez   Laptop Pro
...          ...          ...
1195  Luis Gomez   Raton Ergo
1196  Marta Ruiz   Laptop Pro
1197  Ana Torres   Monitor 27
1198  Ana Torres   Monitor 27
1199  Marta Ruiz   Raton Ergo

[200 rows x 2 columns]

ILOC

Localiza como el slicing similar a python nativo, similar a las listas

In [13]:
ventas_df.iloc[0:4]

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
0,2024-01-02,Oeste,Pedro Diaz,Auriculares,Accesorios,5,130,0.0
1,2024-01-02,Sur,Luis Gomez,Monitor 27,Tecnologia,14,320,0.0
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.0
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.0

In [15]:
# Indexando con "iloc" las filas, pero en el caso de las columnas no se lista, sino que se indexa con el numero de columna, en este caso 0 y 1
ventas_df.iloc[0:4, 0:2]

        fecha  region
0  2024-01-02   Oeste
1  2024-01-02     Sur
2  2024-01-02  Centro
3  2024-01-02  Centro

SORTING DE COLUMNAS

In [17]:
ventas_df.sort_values(by="unidades", ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
17,2024-01-06,Oeste,Marta Ruiz,Laptop Pro,Tecnologia,1,1200,0.00
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
7,2024-01-03,Norte,Sofia Leon,Silla Ergo,Mobiliario,1,280,0.00
54,2024-01-17,Norte,Luis Gomez,Silla Ergo,Mobiliario,1,280,0.00
491,2024-06-07,Centro,Ana Torres,Raton Ergo,Accesorios,1,45,0.15
...,...,...,...,...,...,...,...,...
62,2024-01-21,Este,Elena Mora,Silla Ergo,Mobiliario,14,280,0.00
63,2024-01-21,Este,Pedro Diaz,Silla Ergo,Mobiliario,14,280,0.10
75,2024-01-26,Sur,Luis Gomez,Escritorio,Mobiliario,14,450,0.00
828,2024-09-12,Centro,Ana Torres,Raton Ergo,Accesorios,14,45,0.05
841,2024-09-16,Sur,Carlos Vega,Teclado Mec,Accesorios,14,95,0.00

In [19]:
ventas_df.sort_values(by="precio_unitario", ascending=False)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
301,2024-04-03,Norte,Carlos Vega,Laptop Pro,Tecnologia,2,1200,0.00
875,2024-09-26,Centro,Javier Sanz,Laptop Pro,Tecnologia,8,1200,0.10
871,2024-09-25,Sur,Luis Gomez,Laptop Pro,Tecnologia,14,1200,0.05
868,2024-09-24,Norte,Elena Mora,Laptop Pro,Tecnologia,6,1200,0.00
310,2024-04-08,Oeste,Sofia Leon,Laptop Pro,Tecnologia,10,1200,NaN
...,...,...,...,...,...,...,...,...
1187,2024-12-28,Este,Ana Torres,Raton Ergo,Accesorios,8,45,0.05
274,2024-03-27,Norte,Javier Sanz,Raton Ergo,Accesorios,2,45,0.00
1193,2024-12-30,Centro,Ana Torres,Raton Ergo,Accesorios,7,45,0.00
425,2024-05-15,Sur,Ana Torres,Raton Ergo,Accesorios,10,45,0.10
428,2024-05-15,Centro,Ana Torres,Raton Ergo,Accesorios,9,45,0.00

In [20]:
ventas_df.sort_values(by=["region", "unidades"], ascending=True)

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
2,2024-01-02,Centro,Carlos Vega,Silla Ergo,Mobiliario,1,280,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
26,2024-01-09,Centro,Sofia Leon,Teclado Mec,Accesorios,1,95,0.00
70,2024-01-24,Centro,Luis Gomez,Auriculares,Accesorios,1,130,0.10
98,2024-02-03,Centro,Ana Torres,Monitor 27,Tecnologia,1,320,NaN
...,...,...,...,...,...,...,...,...
1080,2024-11-26,Sur,Javier Sanz,Escritorio,Mobiliario,14,450,0.10
1081,2024-11-26,Sur,Marta Ruiz,Monitor 27,Tecnologia,14,320,0.05
1086,2024-11-28,Sur,Sofia Leon,Laptop Pro,Tecnologia,14,1200,0.15
1130,2024-12-09,Sur,Pedro Diaz,Teclado Mec,Accesorios,14,95,0.15
1181,2024-12-25,Sur,Ana Torres,Tablet Air,Tecnologia,14,640,0.00

In [21]:
ventas_df.sort_values(by=["region", "precio_unitario"], ascending=[True, False])

,fecha,region,vendedor,producto,categoria,unidades,precio_unitario,descuento
3,2024-01-02,Centro,Pedro Diaz,Laptop Pro,Tecnologia,10,1200,0.00
8,2024-01-03,Centro,Carlos Vega,Laptop Pro,Tecnologia,1,1200,0.10
16,2024-01-06,Centro,Ana Torres,Laptop Pro,Tecnologia,13,1200,0.00
40,2024-01-14,Centro,Marta Ruiz,Laptop Pro,Tecnologia,12,1200,0.10
156,2024-02-17,Centro,Pedro Diaz,Laptop Pro,Tecnologia,12,1200,0.05
...,...,...,...,...,...,...,...,...
918,2024-10-09,Sur,Carlos Vega,Raton Ergo,Accesorios,8,45,0.00
1034,2024-11-07,Sur,Javier Sanz,Raton Ergo,Accesorios,4,45,0.15
1058,2024-11-16,Sur,Marta Ruiz,Raton Ergo,Accesorios,2,45,0.10
1063,2024-11-19,Sur,Elena Mora,Raton Ergo,Accesorios,8,45,0.10
1096,2024-12-02,Sur,Javier Sanz,Raton Ergo,Accesorios,12,45,0.00